name: Curriculum Solution Branch Splitter

on:
  push:
    branches: curriculum
    paths: index.ipynb

jobs:
  Sync_Branches:
    uses: learn-co-curriculum/dsc-github-actions-files/.github/workflows/branch_split.yml@v1.0.1
    secrets: inherit
   
